name: CI Check (Linux)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-check:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: yuriy-chumak/ol
        ref: master
    - run: make
    - run: sudo make install

    - uses: actions/checkout@v3
    - name: make check
      run: |
        ol --version
        export LD_LIBRARY_PATH=.
        make all check
