name: CI Check (MacOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-check:
    strategy:
      matrix:
        os: [ macos-14, macos-12, macos-11 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: yuriy-chumak/ol
        ref: master
    - run: make
    - run: sudo make install

    - uses: actions/checkout@v3
    - name: make check
      run: |
        ol --version
        export LD_LIBRARY_PATH=.
        make check-reference
