name: CI Build with Tests (Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        repository: yuriy-chumak/ol
        ref: master
    - run: make
    - run: sudo make install

    - uses: actions/checkout@v2
    - run: |
        export LD_LIBRARY_PATH=.
        make all check
